# Generated by Django 5.0.1 on 2024-02-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=10)),
                ('msg', models.CharField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='base',
        ),
    ]
