# Generated by Django 5.0.1 on 2024-02-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0003_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='name',
            new_name='fname',
        ),
    ]
