# Generated by Django 5.0.1 on 2024-02-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0004_rename_name_reg_fname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg',
        ),
    ]
