# Generated by Django 5.0.1 on 2024-03-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='des',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
