# Generated by Django 5.0.1 on 2024-03-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='des',
        ),
    ]
