# Generated by Django 5.0.1 on 2024-03-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0009_remove_order_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100, null=True, unique=True)),
                ('price', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
