# Generated by Django 5.0.1 on 2025-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0010_orderlist_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='auction_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='des',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
