# Generated by Django 5.0.1 on 2025-04-14 19:07

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0011_image_auction_end_time_image_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bids',
                to='Eauction.image',
                null=True  # 👈 Allow NULL values for existing records
            ),
        ),
    ]
