# Generated by Django 5.0.1 on 2025-04-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0012_orderlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='product',
        ),
    ]
