# Generated by Django 5.0.1 on 2025-04-14 19:17

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0013_remove_orderlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='status',
        ),
        migrations.AlterField(
            model_name='image',
            name='auction_end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 19, 16, 59, 309255, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='des',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
