# Generated by Django 5.0.1 on 2025-04-15 17:04

import Eauction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eauction', '0014_remove_image_status_alter_image_auction_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='auction_end_time',
            field=models.DateTimeField(default=Eauction.models.get_auction_end_time),
        ),
    ]
